# Generated by Django 3.1.2 on 2021-01-16 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_user_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userC',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='userC', to='auctions.user'),
            preserve_default=False,
        ),
    ]
