# Generated by Django 3.1.2 on 2021-01-17 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment_listingc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='listingC',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='listingC', to='auctions.listing'),
        ),
    ]
