# Generated by Django 3.1.2 on 2021-01-18 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210118_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='listingB',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listingB', to='auctions.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='userB',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userB', to='auctions.user'),
            preserve_default=False,
        ),
    ]
