# Generated by Django 3.1.2 on 2021-01-19 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210118_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='userL',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userL', to='auctions.user'),
            preserve_default=False,
        ),
    ]
