# Generated by Django 3.1.2 on 2021-01-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210123_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='previous',
        ),
    ]
