# Generated by Django 3.1.2 on 2021-01-29 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_listing_previous'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winnerB', models.DecimalField(decimal_places=2, max_digits=10)),
                ('winnerL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winnerL', to='auctions.listing')),
                ('winnerU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winnerU', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
