# Generated by Django 3.1.2 on 2021-02-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_listing_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('mobile', 'Mobile'), ('watch', 'Watch'), ('other', 'Other')], max_length=64),
        ),
    ]
