# Generated by Django 3.1.2 on 2021-02-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20210204_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.AlterField(
            model_name='listing',
            name='imageUrl',
            field=models.URLField(default='https://www.thermaxglobal.com/wp-content/uploads/2020/05/image-not-found.jpg'),
            preserve_default=False,
        ),
    ]
