# Generated by Django 3.1.2 on 2021-02-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210205_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageUrl',
            field=models.URLField(default='https://www.thermaxglobal.com/wp-content/uploads/2020/05/image-not-found.jpg'),
        ),
    ]
