# Generated by Django 3.1.2 on 2021-02-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210210_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Laptop', 'laptop'), ('Mobile', 'mobile'), ('Watch', 'watch'), ('Other', 'other')], max_length=64),
        ),
    ]
