# Generated by Django 3.1.2 on 2021-02-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20210215_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Laptop', 'laptop'), ('Mobile', 'mobile'), ('Watch', 'watch'), ('other', 'other')], max_length=64),
        ),
    ]
