# Generated by Django 3.2.6 on 2021-08-31 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateNtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
