# Generated by Django 3.2.6 on 2021-09-17 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_user_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userspost', to=settings.AUTH_USER_MODEL),
        ),
    ]
